// <auto-generated />
using System;
using AutoWay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoWay.Migrations
{
    [DbContext(typeof(AutoWayContext))]
    [Migration("20251021073549_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoWay.AutoWay.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<int>("AvisID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrixFinal")
                        .HasColumnType("float");

                    b.Property<int>("UtilisateurID")
                        .HasColumnType("int");

                    b.Property<int>("VoitureID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("AvisID");

                    b.HasIndex("UtilisateurID");

                    b.HasIndex("VoitureID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AutoWay.Models.Avis", b =>
                {
                    b.Property<int>("AvisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvisID"));

                    b.Property<DateTime>("AvisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AvisMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvisScore")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("AvisID");

                    b.HasIndex("ReservationID")
                        .IsUnique();

                    b.ToTable("Avis");
                });

            modelBuilder.Entity("AutoWay.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilisateurID")
                        .HasColumnType("int");

                    b.HasKey("RoleID");

                    b.HasIndex("UtilisateurID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AutoWay.Models.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilisateurID"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtilisateurID");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("AutoWay.Models.Voiture", b =>
                {
                    b.Property<int>("VoitureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoitureID"));

                    b.Property<bool?>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaqueImm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrixJournalier")
                        .HasColumnType("float");

                    b.Property<int>("UtilisateurID")
                        .HasColumnType("int");

                    b.HasKey("VoitureID");

                    b.HasIndex("UtilisateurID");

                    b.ToTable("Voiture");
                });

            modelBuilder.Entity("AutoWay.AutoWay.Models.Reservation", b =>
                {
                    b.HasOne("AutoWay.Models.Avis", "Avis")
                        .WithMany()
                        .HasForeignKey("AvisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoWay.Models.Utilisateur", "Utilisateur")
                        .WithMany("Reservations")
                        .HasForeignKey("UtilisateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoWay.Models.Voiture", "Voiture")
                        .WithMany("Reservations")
                        .HasForeignKey("VoitureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avis");

                    b.Navigation("Utilisateur");

                    b.Navigation("Voiture");
                });

            modelBuilder.Entity("AutoWay.Models.Avis", b =>
                {
                    b.HasOne("AutoWay.AutoWay.Models.Reservation", "Reservation")
                        .WithOne()
                        .HasForeignKey("AutoWay.Models.Avis", "ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AutoWay.Models.Role", b =>
                {
                    b.HasOne("AutoWay.Models.Utilisateur", null)
                        .WithMany("Roles")
                        .HasForeignKey("UtilisateurID");
                });

            modelBuilder.Entity("AutoWay.Models.Voiture", b =>
                {
                    b.HasOne("AutoWay.Models.Utilisateur", "Utilisateur")
                        .WithMany("Voitures")
                        .HasForeignKey("UtilisateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AutoWay.Models.Utilisateur", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Roles");

                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("AutoWay.Models.Voiture", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
